### PR TITLE
Add My Project kwdb

### PR DESCRIPTION
**Pull request by KsRyY**
My project `kwdb` is a REST wrapper for LevelDB

### CODE REVIEW

**Comment by vweevers** [comment]
Thanks for sharing your work! ❤️ 

I'm wondering about something: does it wrap LevelDB or RocksDB? Because I noticed [`rocksdb` in the dependencies](https://github.com/KsRyY/kwdb/blob/c5b3bfb58ea669ddc74c22e0513ab38f668a8140/package.json#L31).

**Comment by KsRyY** [comment]
The v1.1.0 wraps RocksDB, other version wraps LevelDB because I had found out that rocksDB is too big
@vweevers

**Comment by KsRyY** [comment]
@vweevers

**Comment by vweevers** [comment]
I'll get to this, I promise. There's other work with higher priority.

**Comment by KsRyY** [comment]
OK, I know, thanks

**Comment by vweevers** [comment]
Added in e8c23b211386e7b92e19f068863f99beb38e959d. Instead of saying "`kwdb` is newer" I updated the description of `level-rest` to say it's incompatible with latest `levelup`.

Thanks!

**Pull request closed without merging**
